services:
  db:
    image: bitnami/mongodb:7.0.14
    ports:
      - '27017:27017'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    restart: always

volumes:
  mongodb_data: